### ISSUE TITLE
"Error 1067: The process terminated unexpectedly" on Windows 10

### ISSUE THREAD

**Issue by JeremyRand** [hlandau/service#14]
# Steps to reproduce

1. Build the "Standard Interface" usage example from `README.md` for Windows amd64.
2. Place the binary in a Windows 10 directory that's in the `PATH`.
3. Run the binary in an elevated command prompt with the `-service.do=install` argument.
4. In the Services window, start the `Foobar Web Server` service.

# Expected results

The service should start.

# Observed results

~~~
Windows could not start the Foobar Web Server service on Local Computer.

Error 1067: The process terminated unexpectedly.
~~~

# Other information

* The same steps work fine on Windows 7.
* `btcd` v0.21.0-beta is unaffected; `btcd` uses the `btcsuite` dependencies that `service` also uses, so it's probably not a bug in those dependencies -- or if it is, it's a bug that `btcd` doesn't expose but `service` does.
* ncdns is affected.

**Comment by jonasbits** [comment]
I get Error 1067 on Windows 10 and btcd latest beta does run as a service.

**Comment by JeremyRand** [comment]
This bug is only hit when running with `-buildmode=pie`, which was added for Windows in Go 1.15.  Building with `-buildmode=exe` (which was the default prior to Go 1.15) results in the bug not happening.  `btcd` is equally affected as this repo, but I guess `btcd`'s official binaries have PIE disabled.
