### ISSUE TITLE
Look into setuid/setgid without cgo

### ISSUE THREAD

**Issue by JeremyRand** [hlandau/service#16]
The [Go 1.16 release notes](https://golang.org/doc/go1.16#syscall) state:

> On Linux, Setgid, Setuid, and related calls are now implemented. Previously, they returned an syscall.EOPNOTSUPP error.
> 
> On Linux, the new functions AllThreadsSyscall and AllThreadsSyscall6 may be used to make a system call on all Go threads in the process. These functions may only be used by programs that do not use cgo; if a program uses cgo, they will always return syscall.ENOTSUP. 

So, it sounds like we can maybe drop the cgo requirement for `setuid`/`setgid`.

**Comment by hlandau** [comment]
Implemented and tagged hlandau/svcutils v1.0.11.
