### ISSUE TITLE
Build errors on OS-X (darwin support)

### ISSUE THREAD

**Issue by brightcode** [hlandau/service#2]
I get build errors on OS-X:

    # gopkg.in/hlandau/service.v1/daemon/setuid
    gopkg.in/hlandau/service.v1/daemon/setuid/setuid_other.go:20: undefined: syscall.Setresgid
    gopkg.in/hlandau/service.v1/daemon/setuid/setuid_other.go:24: undefined: syscall.Setresuid
    # gopkg.in/hlandau/service.v1/passwd
    gopkg.in/hlandau/service.v1/passwd/pwnam.c:20:16: error: use of undeclared identifier '_SC_GETPW_R_SIZE_MAX'
    gopkg.in/hlandau/service.v1/passwd/pwnam.c:50:16: error: use of undeclared identifier '_SC_GETGR_R_SIZE_MAX'
    gopkg.in/hlandau/service.v1/passwd/pwnam.c:82:16: error: use of undeclared identifier '_SC_GETGR_R_SIZE_MAX'
    gopkg.in/hlandau/service.v1/passwd/pwnam.c:120:16: error: use of undeclared identifier '_SC_GETGR_R_SIZE_MAX'

This is probably due to lack of darwin support? Maybe this [commit](https://github.com/tobert/sprok/commit/93fb8cf9637326a0ecc3309f06280132766c4604) shows how to fix it?

**Comment by hlandau** [comment]
It would be nice if the passwd package could be replaced with Go's os/user, but os/user provides no means to resolve group names or get the additional GIDs...

That commit is a nice find. I've pushed fixes for both of the above, and service now builds on OSX, which has been added to travis. Of course this doesn't guarantee it will work - let me know how you get on.

**Comment by brightcode** [comment]
Thanks, this is working now on Mac:

    go get -u gopkg.in/hlandau/service.v1
