### ISSUE TITLE
libcap-devel required by Fedora

### ISSUE THREAD

**Issue by leifmadsen** [hlandau/service#3]
I noticed that you've added libcap-dev as a required package under apt in the travis.yml file. Might want to consider doing a libcap-devel for Fedora as well? (not familiar with travis currently, sorry if this seems like a silly suggestion).

Additionally it might be nice to add some documentation about required development dependencies as this bit me for a little bit.

(I'll try and create a pull request tomorrow.)

**Comment by hlandau** [comment]
Thanks. Since Travis is set up to use Ubuntu, I'm not sure that there's any sense in expressing Fedora dependencies, nor am I sure it's even possible.

I'll add a note to advise people that they should install libcap-dev/libcap-devel/etc.

**Comment by leifmadsen** [comment]
Awesome thanks for the quick turn around!
