### ISSUE TITLE
1.0.7 seems to fail to build (at least with gb build)

### ISSUE THREAD

**Issue by leifmadsen** [hlandau/service#4]
We use getgb.io to manage our dependencies, and I was able to build our code with 1.0.6 (since 1.0.7 wasn't tagged yesterday). I ran into an issue with the `-daemon` stuff not working, and noticed a bunch of changes in that area, so thought I'd run a `gb vendor update` and rebuild.

When running `gb build` however, I get the following:

```bash
/tmp/gb296122902/gopkg.in/hlandau/service.v1/daemon/_cgo_gotypes.go:3: package setuid; expected caps
/home/lmadsen/src/avoxi/api-proxy/vendor/src/gopkg.in/hlandau/service.v1/daemon/caps/caps_linux.go:70[/tmp/gb296122902/gopkg.in/hlandau/service.v1/daemon/caps_linux.cgo1.go:17]: undefined: _Cfunc_hasanycap
/home/lmadsen/src/avoxi/api-proxy/vendor/src/gopkg.in/hlandau/service.v1/daemon/caps/caps_linux.go:74[/tmp/gb296122902/gopkg.in/hlandau/service.v1/daemon/caps_linux.cgo1.go:23]: undefined: _Cfunc_dropcaps
github.com/ErikDubbelboer/gspt
config
FATAL command "build" failed: exit status 1
```

**Comment by hlandau** [comment]
If a normal go build `gopkg.in/hlandau/service.v1/...` works fine, this is surely a bug in gb; presumably gb isn't supposed to change the semantics of package layout, etc. and work with any valid go package.

Note how `daemon/caps/*.go` seems to have been moved to `daemon/*.go`.

I'm not familiar with gb, but maybe to start with try deleting the service.v1 directory and redownloading?

**Comment by leifmadsen** [comment]
You can close this. The issue is on the gb side of things. I believe it is related to some open issues on that project. I validated this builds cleanly with a project that is built with traditional `go build`.

Possibly related to an issue like https://github.com/constabulary/gb/issues/331

**Comment by leifmadsen** [comment]
FYI anyone using `gb`, this should be resolved via https://github.com/constabulary/gb/issues/372 now.
